INSERT INTO stories (title, content, creator_id, created_date, completed_date, public, deleted)
VALUES
('The Whispering Woods', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vitae quam nec sem maximus efficitur.', 1, '2024-01-20', '2024-02-05', TRUE, FALSE),
('Echoes of Elysium', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', 2, '2024-01-18', '2024-02-01', TRUE, FALSE),
('Secrets of Seraphina', 'Nulla facilisi. Aenean nec ante non libero condimentum sollicitudin.', 3, '2024-01-25', '2024-02-10', TRUE, FALSE),
('Shadows of Sorrow', 'Sed fermentum elit vel velit interdum tincidunt. Donec volutpat ex eu risus ultrices tristique.', 4, '2024-01-22', '2024-02-07', TRUE, FALSE),
('Whispers in the Wind', 'Suspendisse potenti. In hac habitasse platea dictumst. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.', 5, '2024-01-19', '2024-02-03', TRUE, FALSE),
('The Forgotten Kingdom', 'Vivamus tincidunt consequat velit, nec bibendum mi bibendum eget. Integer in urna auctor, aliquam metus nec, sagittis neque.', 6, '2024-01-24', '2024-02-08', TRUE, FALSE),
('Legends of Lysandra', 'Fusce et nisl eu velit malesuada ultricies. Vestibulum mattis felis sit amet nunc pharetra dignissim.', 7, '2024-01-23', '2024-02-09', TRUE, FALSE),
('Chronicles of Caelum', 'Maecenas ornare nisl justo, vel molestie est tempor nec. In in sapien vel justo facilisis feugiat.', 8, '2024-01-21', '2024-02-06', TRUE, FALSE),
('The Enchanted Isles', 'Quisque ut eros id libero scelerisque vestibulum ac sed risus. Proin vel scelerisque lacus, id tristique purus.', 9, '2024-01-26', '2024-02-11', TRUE, FALSE),
('Tales of Thalassa', 'Praesent euismod congue turpis, vel iaculis libero consequat sed. Integer id gravida est.', 10, '2024-01-17', '2024-01-31', TRUE, FALSE),
('The Phoenix Rising', 'Donec vel nisi aliquet, mollis odio et, sodales leo. Aenean hendrerit, nisi ut sagittis vestibulum, urna leo commodo sapien, a varius tortor libero eget elit.', 11, '2024-01-16', '2024-01-30', TRUE, FALSE),
('Aurora''s Awakening', 'Aliquam aliquam diam vel commodo efficitur. Pellentesque vel orci elementum, commodo lorem non, ultricies ipsum.', 12, '2024-01-15', '2024-01-29', TRUE, FALSE),
('The Silver Serpent', 'Vestibulum sed ex ut ipsum interdum malesuada. Integer sit amet ex vel magna lobortis mattis.', 13, '2024-01-14', '2024-01-28', TRUE, FALSE),
('The Veil of Vespera', 'Nam rutrum ligula quis scelerisque interdum. Praesent luctus scelerisque felis vel accumsan.', 14, '2024-01-13', '2024-01-27', TRUE, FALSE),
('The Lost Empire', 'Ut fermentum consequat dui, sed faucibus risus congue vitae. Sed dictum tempor mi, id iaculis elit. ', 15, '2024-01-12', '2024-01-26', TRUE, FALSE),
('The Crown of Corvus', 'Curabitur quis lectus sed leo tempus placerat. Phasellus in lacus lorem. Proin ac ipsum felis.', 16, '2024-01-11', '2024-01-25', TRUE, FALSE),
('The Elysian Fields', 'Aliquam eget ultrices turpis, eu ultricies dui. Vivamus sed sapien vel sapien bibendum efficitur.', 17, '2024-01-10', '2024-01-24', TRUE, FALSE),
('The Song of Sylph', 'Mauris non enim in tortor pharetra eleifend at nec purus. Duis vitae mi ut mauris vulputate tincidunt.', 18, '2024-01-09', '2024-01-23', TRUE, FALSE),
('Echoes of Eldoria', 'Nulla hendrerit, augue a convallis vestibulum, neque nisl tempus lacus, vel scelerisque felis mi eget magna.', 19, '2024-01-08', '2024-01-22', TRUE, FALSE),
('Whispers of Wysteria', 'Maecenas consectetur purus ac libero rutrum, et dictum libero suscipit. Nullam vel nulla vel purus vestibulum auctor.', 20, '2024-01-07', '2024-01-21', TRUE, FALSE),
('The Serenade of Selene', 'Vivamus efficitur eros ac ligula venenatis fermentum. Duis in felis sapien.', 21, '2024-01-06', '2024-01-20', TRUE, FALSE),
('Legends of Lyra', 'Suspendisse id ante at libero dignissim finibus. Fusce id ante ac arcu bibendum malesuada.', 22, '2024-01-05', '2024-01-19', TRUE, FALSE),
('The Chronicles of Celestia', 'Nunc vitae sodales sapien. Morbi mattis, metus vel aliquet volutpat, metus magna placerat sapien, at vestibulum felis felis et est.', 23, '2024-01-04', '2024-01-18', TRUE, FALSE),
('The Whispers of Winter', 'Aliquam pretium congue tincidunt. Sed auctor ante in est rhoncus, eu dictum lacus mollis.', 24, '2024-01-03', '2024-01-17', TRUE, FALSE),
('The Mystic Mirror', 'Donec elementum velit sit amet magna euismod, et euismod velit varius. Phasellus ut condimentum ex.', 25, '2024-01-02', '2024-01-16', TRUE, FALSE),
('The Legend of Avalon', 'Sed viverra elit quis orci gravida, nec pharetra lorem dictum. Integer consectetur libero non nibh condimentum, id efficitur purus tincidunt.', 1, '2024-01-01', '2024-01-15', TRUE, FALSE),
('The Enigma of Eirene', 'Vestibulum condimentum velit nec est ultrices, quis convallis felis tempus. Fusce nec ex a magna placerat ullamcorper nec eu eros.', 2, '2023-12-31', '2024-01-14', TRUE, FALSE),
('The Whispering Willow', 'Nulla facilisi. Phasellus sed purus vitae sapien elementum volutpat. Aliquam erat volutpat.', 3, '2023-12-30', '2024-01-13', TRUE, FALSE),
('Echoes of Euphoria', 'Aliquam erat volutpat. Donec ullamcorper justo nec ipsum sodales scelerisque. Nullam tincidunt nisl vel dictum accumsan.', 4, '2023-12-29', '2024-01-12', TRUE, FALSE),
('The Enchanted Oak', 'Praesent fermentum dui vitae justo interdum, ut consectetur quam laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', 5, '2023-12-28', '2024-01-11', TRUE, FALSE),
('The Serenity of Sapphira', 'Sed eu erat quis augue ultrices facilisis. Suspendisse nec velit et arcu condimentum condimentum.', 6, '2023-12-27', '2024-01-10', TRUE, FALSE),
('The Journey of Juno', 'Nam vel mi malesuada, dictum nisi vel, rhoncus libero. In hac habitasse platea dictumst.', 7, '2023-12-26', '2024-01-09', TRUE, FALSE),
('The Legacy of Lysander', 'Pellentesque quis ipsum dictum, molestie mi in, commodo nibh. Proin condimentum pharetra pharetra.', 8, '2023-12-25', '2024-01-08', TRUE, FALSE),
('The Odyssey of Ophelia', 'Nullam ultricies mi nec sem fringilla accumsan. Sed dignissim justo eget augue tincidunt, id rhoncus arcu ultrices.', 9, '2023-12-24', '2024-01-07', TRUE, FALSE),
('The Prophecy of Pandora', 'Suspendisse vitae justo vitae eros gravida lobortis nec et mi. Integer ullamcorper varius volutpat.', 10, '2023-12-23', '2024-01-06', TRUE, FALSE),
('The Echoes of Eldorado', 'Curabitur scelerisque metus et dictum molestie. Sed non est ut nisi bibendum congue id a urna.', 11, '2023-12-22', '2024-01-05', TRUE, FALSE),
('The Dawn of Delphi', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris tincidunt dolor ut est suscipit, nec vehicula justo vestibulum.', 12, '2023-12-21', '2024-01-04', TRUE, FALSE),
('The Chronicles of Cassandra', 'Suspendisse eu enim consectetur, bibendum enim id, feugiat nunc. Phasellus fringilla nisi ac dui convallis, at faucibus dolor facilisis.', 13, '2023-12-20', '2024-01-03', TRUE, FALSE),
('The Quest for Quetzalcoatl', 'Fusce convallis est nec libero fringilla, at faucibus quam facilisis. Praesent rutrum tortor id erat cursus, eget varius nulla efficitur.', 14, '2023-12-19', '2024-01-02', TRUE, FALSE),
('The Legacy of Lancelot', 'Donec bibendum metus vel ligula tempus, non congue magna suscipit. Maecenas vel ex vitae nulla fermentum rutrum.', 15, '2023-12-18', '2024-01-01', TRUE, FALSE),
('The Whispering Waters', 'Morbi non enim auctor, varius enim vel, scelerisque eros. Ut nec justo nec eros sollicitudin tincidunt.', 16, '2023-12-17', '2023-12-31', TRUE, FALSE),
('The Legend of Luminara', 'Phasellus viverra nisi sit amet purus consectetur dignissim. Fusce a odio a elit lobortis rutrum.', 17, '2023-12-16', '2023-12-30', TRUE, FALSE),
('The Quest for Quasar', 'Vivamus vitae dui a magna volutpat rutrum. Vestibulum feugiat lorem ut dolor congue, ac auctor turpis placerat.', 18, '2023-12-15', '2023-12-29', TRUE, FALSE),
('The Odyssey of Orion', 'Proin sit amet nulla at justo tempor vehicula. Cras hendrerit ipsum at ultrices sodales.', 19, '2023-12-14', '2023-12-28', TRUE, FALSE),
('The Secrets of Sargasso', 'Quisque sit amet urna in nisi fringilla maximus. Donec ac libero sed nisi rutrum bibendum.', 20, '2023-12-13', '2023-12-27', TRUE, FALSE),
('The Lost Labyrinth', 'Fusce eleifend ex eu odio hendrerit, vitae scelerisque nulla viverra. Nam auctor convallis mi, a feugiat metus pharetra et.', 21, '2023-12-12', '2023-12-26', TRUE, FALSE),
('The Whispering Wasteland', 'Integer convallis velit vitae congue suscipit. Nullam id mauris in justo euismod fermentum.', 22, '2023-12-11', '2023-12-25', TRUE, FALSE),
('The Oracle of Olympus', 'Vestibulum at velit in dui tincidunt consequat. Integer eu mi a ex rutrum dignissim.', 23, '2023-12-10', '2023-12-24', TRUE, FALSE),
('The Enigma of Elara', 'Sed rutrum tellus at dui interdum, sed laoreet nisl tincidunt. Integer tincidunt ante ac nunc laoreet, sed rhoncus ante euismod.', 24, '2023-12-09', '2023-12-23', TRUE, FALSE),
('The Quest for Quetzal', 'Fusce in ligula in libero sodales cursus a vel libero. Nullam vestibulum felis vitae nunc convallis bibendum.', 25, '2023-12-08', '2023-12-22', TRUE, FALSE),

('The Legend of Lemuria', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac tellus vel elit volutpat dignissim.', 1, '2023-12-07', '2023-12-21', TRUE, FALSE),
('The Mystery of Mithras', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel dapibus libero.', 2, '2023-12-06', '2023-12-20', TRUE, FALSE),
('The Saga of Sisyphus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id mauris sit amet justo accumsan interdum.', 3, '2023-12-05', '2023-12-19', TRUE, FALSE),
('The Legacy of Laelaps', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lacinia felis non tellus sodales.', 4, '2023-12-04', '2023-12-18', TRUE, FALSE),
('The Quest for Quinella', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas scelerisque magna quis ultricies consectetur.', 5, '2023-12-03', '2023-12-17', TRUE, FALSE),
('The Echoes of Echidna', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus at neque ac tortor cursus pharetra.', 6, '2023-12-02', '2023-12-16', TRUE, FALSE),
('The Oath of Orpheus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum tellus quis orci accumsan, a efficitur mi congue.', 7, '2023-12-01', '2023-12-15', TRUE, FALSE),
('The Fables of Faunus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at velit non nisi accumsan eleifend.', 8, '2023-11-30', '2023-12-14', TRUE, FALSE),
('The Enchantment of Eos', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis quam eu purus convallis posuere.', 9, '2023-11-29', '2023-12-13', TRUE, FALSE),
('The Odyssey of Orestes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac ante nec felis tincidunt gravida.', 10, '2023-11-28', '2023-12-12', TRUE, FALSE),
('The Secrets of Selene', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat.', 11, '2023-11-27', '2023-12-11', TRUE, FALSE),
('The Lore of Lycaon', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc id elit nec libero auctor fermentum.', 12, '2023-11-26', '2023-12-10', TRUE, FALSE),
('The Echoes of Endymion', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eu dolor in lectus fermentum posuere.', 13, '2023-11-25', '2023-12-09', TRUE, FALSE),
('The Prophecy of Proteus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum vitae lorem id gravida.', 14, '2023-11-24', '2023-12-08', TRUE, FALSE),
('The Quest for Querela', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultricies orci a nunc ultrices consequat.', 15, '2023-11-23', '2023-12-07', TRUE, FALSE),
('The Mystery of Morpheus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lacus quis felis maximus volutpat.', 16, '2023-11-22', '2023-12-06', TRUE, FALSE),
('The Legacy of Lycomedes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sit amet sapien nec leo malesuada vehicula.', 17, '2023-11-21', '2023-12-05', TRUE, FALSE),
('The Enigma of Echidna', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque hendrerit nec ex nec volutpat.', 18, '2023-11-20', '2023-12-04', TRUE, FALSE),
('The Whispering Willows', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ullamcorper orci vitae justo hendrerit.', 19, '2023-11-19', '2023-12-03', TRUE, FALSE),
('The Chronicles of Charon', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum diam vel odio dictum, nec interdum nulla malesuada.', 20, '2023-11-18', '2023-12-02', TRUE, FALSE),
('The Legend of Ligeia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis nisi ac libero iaculis volutpat.', 21, '2023-11-17', '2023-12-01', TRUE, FALSE),
('The Echoes of Erebus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dignissim lacus nec diam aliquam, vel commodo dolor finibus.', 22, '2023-11-16', '2023-11-30', TRUE, FALSE),
('The Quest for Qilin', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam hendrerit orci et dui dapibus, et scelerisque metus accumsan.', 23, '2023-11-15', '2023-11-29', TRUE, FALSE),
('The Legacy of Lysistrata', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et purus sit amet risus luctus venenatis.', 24, '2023-11-14', '2023-11-28', TRUE, FALSE),
('The Journey of Jason', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec nulla nec enim cursus scelerisque id a dolor.', 25, '2023-11-13', '2023-11-27', TRUE, FALSE),
('The Whispering Waves', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed mi nec nisl commodo dictum.', 1, '2023-11-12', '2023-11-26', TRUE, FALSE),
('The Prophecy of Perseus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tincidunt est a diam consequat, id tempor felis vestibulum.', 2, '2023-11-11', '2023-11-25', TRUE, FALSE),
('The Enchantment of Elpis', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla congue quam non neque dignissim, sed efficitur metus tempus.', 3, '2023-11-10', '2023-11-24', TRUE, FALSE),
('The Odyssey of Odysseus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu mi vel felis ultrices pharetra.', 4, '2023-11-09', '2023-11-23', TRUE, FALSE),
('The Secrets of Scylla', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean gravida lorem vel ipsum laoreet, non fermentum arcu vulputate.', 5, '2023-11-08', '2023-11-22', TRUE, FALSE),
('The Legacy of Leto', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id purus nec libero fermentum cursus.', 6, '2023-11-07', '2023-11-21', TRUE, FALSE),
('The Echoes of Eirene', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.', 7, '2023-11-06', '2023-11-20', TRUE, FALSE),
('The Enigma of Endymion', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac erat vel leo hendrerit fringilla.', 8, '2023-11-05', '2023-11-19', TRUE, FALSE),
('The Whispering Winds', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel nisi a velit mattis luctus.', 9, '2023-11-04', '2023-11-18', TRUE, FALSE),
('The Quest for Quetzalli', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet nisi non elit vulputate congue.', 10, '2023-11-03', '2023-11-17', TRUE, FALSE),
('The Mystery of Medea', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec nulla in orci mollis blandit id id orci.', 11, '2023-11-02', '2023-11-16', TRUE, FALSE),
('The Legacy of Lyonesse', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at risus non mi accumsan varius.', 12, '2023-11-01', '2023-11-15', TRUE, FALSE),
('The Odyssey of Olympus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque eros at metus hendrerit, eget interdum mi dignissim.', 13, '2023-10-31', '2023-11-14', TRUE, FALSE),
('The Enchantment of Eurydice', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent gravida justo vel lorem interdum, quis sodales libero tempor.', 14, '2023-10-30', '2023-11-13', TRUE, FALSE),
('The Prophecy of Pegasus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ut sapien sed quam efficitur bibendum nec nec nunc.', 15, '2023-10-29', '2023-11-12', TRUE, FALSE),
('The Legacy of Lir', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel ipsum auctor, sagittis dolor sit amet, rutrum magna.', 16, '2023-10-28', '2023-11-11', TRUE, FALSE),
('The Echoes of Elpis', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam consequat est sed est facilisis, id sollicitudin elit vulputate.', 17, '2023-10-27', '2023-11-10', TRUE, FALSE),
('The Whispering Whirlwind', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus est a fringilla feugiat.', 18, '2023-10-26', '2023-11-09', TRUE, FALSE),
('The Quest for Quotidian', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ultrices ex a justo blandit, ac ultricies eros vulputate.', 19, '2023-10-25', '2023-11-08', TRUE, FALSE),
('The Mystery of Mariposa', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce malesuada nulla nec vestibulum feugiat.', 20, '2023-10-24', '2023-11-07', TRUE, FALSE),
('The Legacy of Lamia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus auctor justo ut scelerisque laoreet.', 21, '2023-10-23', '2023-11-06', TRUE, FALSE),
('The Odyssey of Oceania', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed metus nec purus pellentesque aliquam.', 22, '2023-10-22', '2023-11-05', TRUE, FALSE),
('The Enchantment of Elysium', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultricies nisi vel vestibulum tempor.', 23, '2023-10-21', '2023-11-04', TRUE, FALSE),
('The Prophecy of Phoenix', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum felis sit amet elit tempor, vel eleifend neque eleifend.', 24, '2023-10-20', '2023-11-03', TRUE, FALSE),
('The Legacy of Leander', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed purus quis orci efficitur malesuada.', 25, '2023-10-19', '2023-11-02', TRUE, FALSE);

