INSERT INTO stories (title, content, creator_id, completed, created_date, completed_date, public, deleted) VALUES
('The Lost Treasure', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod urna id est sagittis, id posuere sapien fermentum.', 1, TRUE, '2023-01-10', '2023-02-15', TRUE, FALSE),
('The Secret Garden', 'Sed vehicula dui eu massa viverra, quis ultricies sapien efficitur. Nulla facilisi.', 2, FALSE, '2023-02-05', '2023-03-20', TRUE, FALSE),
('The Enchanted Forest', 'Vestibulum ut nulla ac sapien accumsan convallis. Nulla facilisi. Ut fermentum malesuada lorem.', 3, TRUE, '2023-03-20', '2023-05-01', TRUE, FALSE),
('The Mystery Mansion', 'Cras sit amet arcu a quam gravida ullamcorper. Sed dictum sem non dui feugiat, in fermentum urna varius.', 4, FALSE, '2023-04-12', '2023-03-20', TRUE, FALSE),
('The Haunted Castle', 'Nam sit amet ipsum vitae magna rhoncus ultricies nec vitae magna. Phasellus ultrices semper ipsum vel fringilla.', 5, TRUE, '2023-05-30', '2023-07-10', TRUE, FALSE),
('The Forbidden Island', 'Fusce pretium augue eu risus volutpat, sit amet fermentum lectus ultricies. Curabitur hendrerit dictum leo.', 6, FALSE, '2023-06-25', '2023-03-20', TRUE, FALSE),
('The Magic Mirror', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris eget ex ac orci pharetra interdum.', 7, TRUE, '2023-07-15', '2023-09-01', TRUE, FALSE),
('The Time Traveler', 'Ut ut purus in nisi efficitur pharetra. Donec tincidunt risus a magna interdum bibendum.', 8, FALSE, '2023-08-10', '2023-03-20', TRUE, FALSE),
('The Ancient Scroll', 'Integer fermentum enim non libero varius aliquam. Proin euismod arcu nec felis aliquet sollicitudin.', 9, TRUE, '2023-09-20', '2023-11-01', TRUE, FALSE),
('The Cosmic Journey', 'Nulla cursus tellus vel diam ultrices, id facilisis risus accumsan. In congue euismod libero, ac dictum ante blandit ut.', 10, FALSE, '2023-10-05', '2023-03-20', TRUE, FALSE),
('The Galactic War', 'Sed non odio non lectus consequat interdum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', 11, TRUE, '2023-11-30', '2024-01-10', TRUE, FALSE),
('The Robot Revolution', 'Maecenas congue ante nec odio condimentum, eget convallis lorem vestibulum. Sed non arcu non libero finibus finibus.', 12, FALSE, '2023-12-15', '2023-03-20', TRUE, FALSE),
('The Quantum Quest', 'Praesent nec mi nec odio posuere faucibus. Cras ac libero nec velit luctus elementum.', 13, TRUE, '2024-01-20', '2024-03-01', TRUE, FALSE),
('The Dimensional Rift', 'Curabitur lobortis tortor eget nisl varius, nec convallis enim tincidunt. Integer et dui ac odio scelerisque auctor.', 14, FALSE, '2024-02-10', '2023-03-20', TRUE, FALSE),
('The Interstellar Odyssey', 'Nam ut nisl eget justo cursus mattis. Nulla facilisi. Vivamus posuere interdum quam, ut pellentesque lectus vestibulum et.', 15, TRUE, '2024-03-25', '2024-05-05', TRUE, FALSE),
('The Cybernetic Empire', 'Suspendisse vitae orci vel dui consectetur tincidunt. Duis vestibulum ullamcorper felis nec sodales.', 16, FALSE, '2024-04-10', '2023-03-20', TRUE, FALSE),
('The AI Uprising', 'Fusce id lacus vel ex pharetra placerat. Nulla facilisi. Vivamus rutrum velit quis ligula suscipit commodo.', 17, TRUE, '2024-05-20', '2024-07-01', TRUE, FALSE),
('The Virtual Reality', 'Sed eu ante vel quam fermentum dictum. Pellentesque nec orci eu nisi vestibulum bibendum.', 18, FALSE, '2024-06-15', '2023-03-20', TRUE, FALSE),
('The Deep Space Exploration', 'Vivamus sed nisi at mi placerat suscipit. Duis dictum dolor vel quam dictum, nec vulputate sapien egestas.', 19, TRUE, '2024-07-30', '2024-09-10', TRUE, FALSE),
('The Alien Encounter', 'Curabitur sit amet tortor nec magna dictum convallis. Mauris tincidunt ligula ut magna suscipit, at bibendum velit mollis.', 20, FALSE, '2024-08-10', '2023-03-20', TRUE, FALSE),
('The Terraforming Project', 'Nam in sem vitae mauris fermentum luctus. Donec ullamcorper velit ut nisi maximus, ac congue turpis tincidunt.', 21, TRUE, '2024-09-25', '2024-11-05', TRUE, FALSE),
('The Interplanetary Colonization', 'Suspendisse ut nulla vitae nunc dapibus suscipit. Maecenas in elit tincidunt, cursus eros eu, venenatis odio.', 22, FALSE, '2024-10-15', '2023-03-20', TRUE, FALSE),
('The Galactic Council', 'Praesent id odio nec libero dapibus tincidunt. Ut a felis at lorem rutrum pellentesque.', 23, TRUE, '2024-11-30', '2025-01-10', TRUE, FALSE),
('The Cosmic Collapse', 'Donec ac est vel odio vulputate rhoncus. Vivamus nec lorem vitae sapien posuere feugiat.', 24, FALSE, '2024-12-20', '2023-03-20', TRUE, FALSE),
('The Universal Harmony', 'Sed volutpat purus ac odio vehicula, at elementum nisi ultricies. Vestibulum sagittis, orci id molestie volutpat.', 25, TRUE, '2025-01-10', '2025-02-20', TRUE, FALSE),
('The Lost Colony', 'Phasellus non orci id est tincidunt ultrices. Sed condimentum sapien quis nisi euismod dictum.', 26, FALSE, '2025-02-25', '2023-03-20', TRUE, FALSE),
('The Ancient Temple', 'Nullam pretium justo at libero pellentesque, a eleifend arcu facilisis. Sed nec urna at felis auctor tristique.', 27, TRUE, '2025-03-10', '2025-04-20', TRUE, FALSE),
('The Quest for Knowledge', 'Sed tristique metus eget semper eleifend. Vestibulum consequat, leo ac egestas rhoncus, nibh magna consequat nibh.', 28, FALSE, '2025-04-15', '2023-03-20', TRUE, FALSE),
('The Wizard''s Apprentice', 'Fusce auctor ex at diam ultricies, vitae bibendum metus congue. Vivamus convallis tincidunt magna, sit amet malesuada metus.', 29, TRUE, '2025-05-30', '2025-07-10', TRUE, FALSE),
('The Dragon''s Lair', 'Integer in lacus non urna rhoncus vehicula ut non nisi. Aenean a ligula at tortor convallis efficitur.', 30, FALSE, '2025-06-25', '2023-03-20', TRUE, FALSE),
('The Last Knight', 'Morbi fermentum felis sit amet magna lobortis, vel vulputate ipsum tincidunt. Integer tempus nulla nec magna vehicula sollicitudin.', 31, TRUE, '2025-07-15', '2025-09-01', TRUE, FALSE),
('The Pirate''s Curse', 'Curabitur non velit nec eros gravida gravida. Sed faucibus, nulla et malesuada rutrum, nulla risus vehicula metus.', 32, FALSE, '2025-08-10', '2023-03-20', TRUE, FALSE),
('The Ghost Ship', 'Suspendisse nec felis ac nisi viverra tempus. Nam volutpat consectetur ipsum, at interdum tortor lacinia sed.', 33, TRUE, '2025-09-20', '2025-11-01', TRUE, FALSE),
('The Cursed Amulet', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec vehicula purus eget sem fermentum.', 34, FALSE, '2025-10-05', '2023-03-20', TRUE, FALSE),
('The Wandering Bard', 'Ut pharetra enim vel metus dapibus, at placerat risus ultrices. Morbi eleifend turpis sit amet orci varius, ut elementum quam vestibulum.', 35, TRUE, '2025-11-30', '2026-01-10', TRUE, FALSE),
('The Dark Forest', 'Sed maximus eros eget quam tincidunt, eget consequat ligula tempor. Duis eleifend velit nec ultrices molestie.', 36, FALSE, '2025-12-15', '2023-03-20', TRUE, FALSE),
('The Silver Key', 'Quisque efficitur arcu nec justo accumsan, ac ullamcorper arcu semper. Fusce nec odio eu urna sodales consectetur.', 37, TRUE, '2026-01-20', '2026-03-01', TRUE, FALSE),
('The Crystal Cave', 'Nam eu libero non eros ultrices fermentum. Maecenas et purus eget nisl rhoncus lacinia.', 38, FALSE, '2026-02-10', '2023-03-20', TRUE, FALSE),
('The Phoenix Rising', 'Phasellus eget arcu id nisl gravida mattis. Duis non mi vel nulla tincidunt egestas vel et lacus.', 39, TRUE, '2026-03-25', '2026-05-05', TRUE, FALSE),
('The Emerald City', 'Vivamus bibendum velit eget magna placerat, a ultricies enim feugiat. Fusce at augue a elit convallis tincidunt.', 40, FALSE, '2026-04-10', '2023-03-20', TRUE, FALSE),
('The Sleeping Giant', 'Donec tristique purus eget purus tincidunt bibendum. Integer vel neque sit amet libero euismod dictum.', 41, TRUE, '2026-05-30', '2026-07-10', TRUE, FALSE),
('The Crystal Palace', 'Pellentesque euismod eros ut magna rutrum, eget pretium justo fringilla. Nam pharetra arcu sit amet ante dignissim ullamcorper.', 42, FALSE, '2026-06-25', '2023-03-20', TRUE, FALSE),
('The Silver Sword', 'Curabitur a lectus non lorem vehicula vestibulum. Duis posuere augue vel efficitur aliquam.', 43, TRUE, '2026-07-15', '2026-09-01', TRUE, FALSE),
('The Ivory Tower', 'Maecenas vel odio ultricies, lacinia est sit amet, viverra felis. Sed ac hendrerit nisi.', 44, FALSE, '2026-08-10', '2023-03-20', TRUE, FALSE),
('The Crimson Rose', 'Morbi auctor nisi vitae felis volutpat tincidunt. Quisque suscipit, nisl nec dictum fermentum, odio dolor vehicula velit.', 45, TRUE, '2026-09-20', '2026-11-01', TRUE, FALSE),
('The Frozen Wasteland', 'Sed non elit non velit interdum mattis. Proin auctor nunc eu ipsum tristique, nec varius ligula ultricies.', 46, FALSE, '2026-10-05', '2023-03-20', TRUE, FALSE),
('The Golden Compass', 'Nunc quis dolor nec eros interdum auctor eget nec libero. Donec a nisi eleifend, congue neque ac, ullamcorper ipsum.', 47, TRUE, '2026-11-30', '2027-01-10', TRUE, FALSE),
('The Whispers in the Dark', 'Praesent vel enim et mi ultricies vulputate. Integer nec turpis tincidunt, tempor mauris in, faucibus eros.', 48, FALSE, '2026-12-15', '2023-03-20', TRUE, FALSE),
('The Sword of Destiny', 'Morbi eget neque nec turpis maximus ultricies non nec libero. Curabitur vel eros nec arcu elementum malesuada.', 49, TRUE, '2027-01-20', '2027-03-01', TRUE, FALSE),
('The Echoing Caves', 'Nam vel justo nec urna ultrices ullamcorper. Aliquam nec ex eget neque ullamcorper fringilla nec vitae arcu.', 50, FALSE, '2027-02-10', '2023-03-20', TRUE, FALSE),
('The Tower of Sorcery', 'Vestibulum nec leo sed orci efficitur iaculis. Proin non tortor id ligula pharetra sodales.', 51, TRUE, '2027-03-25', '2027-05-05', TRUE, FALSE),
('The Shadowed Path', 'Suspendisse potenti. Sed at elit aliquet, feugiat velit at, dignissim elit. Quisque non sodales libero.', 52, FALSE, '2027-04-10', '2023-03-20', TRUE, FALSE),
('The Crown of Kings', 'Curabitur viverra ipsum non nulla vestibulum consectetur. Morbi fringilla sem nec fermentum ultrices.', 53, TRUE, '2027-05-30', '2027-07-10', TRUE, FALSE),
('The Chalice of Life', 'Fusce congue ligula vitae dolor laoreet, non efficitur ante placerat. Duis feugiat tincidunt quam nec commodo.', 54, FALSE, '2027-06-25', '2023-03-20', TRUE, FALSE),
('The Song of the Sirens', 'Sed eu orci sit amet quam faucibus eleifend. Integer vel purus vitae lacus fermentum faucibus.', 55, TRUE, '2027-07-15', '2027-09-01', TRUE, FALSE),
('The Sands of Time', 'Pellentesque ac nulla luctus, malesuada leo nec, bibendum magna. Sed feugiat mauris at efficitur ultricies.', 56, FALSE, '2027-08-10', '2023-03-20', TRUE, FALSE),
('The Crimson Tide', 'Nullam sagittis eros nec diam rutrum, quis mattis odio varius. Sed vel velit tempor, aliquet est et, volutpat sapien.', 57, TRUE, '2027-09-20', '2027-11-01', TRUE, FALSE),
('The Ivory Key', 'In volutpat dolor id leo laoreet, eget fermentum ligula convallis. Curabitur sed purus eu arcu sollicitudin placerat.', 58, FALSE, '2027-10-05', '2023-03-20', TRUE, FALSE),
('The Emerald Dagger', 'Vivamus luctus sapien nec magna suscipit, sed molestie purus volutpat. Vestibulum ullamcorper, ipsum vel euismod malesuada.', 59, TRUE, '2027-11-30', '2028-01-10', TRUE, FALSE),
('The Midnight Sun', 'Integer suscipit mauris in ex dictum, sed volutpat quam fringilla. Nullam quis odio sit amet ex faucibus malesuada.', 60, FALSE, '2027-12-15', '2023-03-20', TRUE, FALSE),
('The Silver Lining', 'Suspendisse in purus eu eros volutpat ullamcorper. Fusce non tincidunt nibh. Sed luctus interdum erat.', 61, TRUE, '2028-01-20', '2028-03-01', TRUE, FALSE),
('The Golden Horizon', 'Quisque vestibulum turpis vitae risus cursus, ut sollicitudin sapien posuere. Pellentesque a ante ut leo varius ultrices.', 62, FALSE, '2028-02-10', '2023-03-20', TRUE, FALSE),
('The Azure Sky', 'Vestibulum et mi ac eros euismod consequat. Fusce nec nisi id nulla tincidunt ultricies.', 63, TRUE, '2028-03-25', '2028-05-05', TRUE, FALSE),
('The Crimson Blade', 'Pellentesque quis eros sed arcu rutrum vestibulum. Nulla facilisi. In sed lorem nec purus fermentum condimentum.', 64, FALSE, '2028-04-10', '2023-03-20', TRUE, FALSE),
('The Silver Arrow', 'Fusce ac mauris vel orci consectetur tristique. Duis id sem vel nibh tempor fermentum.', 65, TRUE, '2028-05-30', '2028-07-10', TRUE, FALSE),
('The Ruby Ring', 'Integer consequat libero nec velit volutpat, eu gravida justo rhoncus. Fusce non nisi vitae sapien laoreet vulputate.', 66, FALSE, '2028-06-25', '2023-03-20', TRUE, FALSE),
('The Diamond Heart', 'Quisque vitae odio in ante blandit euismod. Cras eget leo quis justo congue aliquam.', 67, TRUE, '2028-07-15', '2028-09-01', TRUE, FALSE),
('The Amethyst Crown', 'Morbi commodo arcu ac odio scelerisque, ac malesuada urna cursus. Curabitur bibendum eros nec tincidunt condimentum.', 68, FALSE, '2028-08-10', '2023-03-20', TRUE, FALSE),
('The Sapphire Scepter', 'Sed fringilla purus vel quam tristique rhoncus. Fusce a orci accumsan, eleifend magna eget, sodales nunc.', 69, TRUE, '2028-09-20', '2028-11-01', TRUE, FALSE),
('The Emerald Staff', 'Nullam tincidunt quam id magna hendrerit, ut lobortis nulla pharetra. Fusce nec lectus et lorem cursus rutrum.', 70, FALSE, '2028-10-05', '2023-03-20', TRUE, FALSE),
('The Topaz Tome', 'Suspendisse sit amet lectus in elit gravida condimentum. Morbi pharetra orci eget sapien consequat, nec hendrerit dolor sollicitudin.', 71, TRUE, '2028-11-30', '2029-01-10', TRUE, FALSE),
('The Garnet Globe', 'Vivamus non augue sit amet nulla maximus feugiat. Mauris accumsan mauris nec vestibulum volutpat.', 72, FALSE, '2028-12-15', '2023-03-20', TRUE, FALSE),
('The Pearl Pendant', 'Donec ultricies ligula ac nisl consequat lobortis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', 73, TRUE, '2029-01-20', '2029-03-01', TRUE, FALSE),
('The Opal Orb', 'Mauris aliquet ipsum id mauris tempor, id tincidunt tortor feugiat. Proin quis est id nunc gravida pharetra.', 74, FALSE, '2029-02-10', '2023-03-20', TRUE, FALSE),
('The Onyx Oath', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi a lorem ac sapien tincidunt consequat.', 75, TRUE, '2029-03-25', '2029-05-05', TRUE, FALSE),
('The Platinum Prism', 'Fusce aliquam augue id justo tempor, in commodo metus lacinia. Curabitur quis elit vel felis hendrerit facilisis.', 76, FALSE, '2029-04-10', '2023-03-20', TRUE, FALSE),
('The Ruby Rod', 'Phasellus varius magna nec leo placerat sollicitudin. Duis nec nisl sed justo ultrices consequat.', 77, TRUE, '2029-05-30', '2029-07-10', TRUE, FALSE),
('The Sapphire Scarab', 'Maecenas nec nisi eu ex convallis fermentum. Vestibulum gravida, felis a ullamcorper rhoncus, ligula felis mollis nisi.', 78, FALSE, '2029-06-25', '2023-03-20', TRUE, FALSE),
('The Obsidian Obelisk', 'Donec auctor ex ac ligula volutpat, quis pharetra mi suscipit. Suspendisse potenti. Aliquam volutpat nunc eget.', 79, TRUE, '2029-07-15', '2029-09-01', TRUE, FALSE),
('The Diamond Diadem', 'Nam sit amet tellus eget est dignissim ultricies. Donec quis ipsum quis est blandit interdum.', 80, FALSE, '2029-08-10', '2023-03-20', TRUE, FALSE),
('The Emerald Elixir', 'Cras vel urna nec lectus venenatis consequat. Nullam vestibulum, arcu id egestas scelerisque, elit risus dapibus quam.', 81, TRUE, '2029-09-20', '2029-11-01', TRUE, FALSE),
('The Garnet Goblet', 'Sed et quam in turpis gravida ultricies. Integer lobortis nisi a mollis commodo.', 82, FALSE, '2029-10-05', '2023-03-20', TRUE, FALSE),
('The Golden Goblet', 'Suspendisse quis purus nec leo facilisis mollis. Cras quis est varius, bibendum nisl vel, finibus odio.', 83, TRUE, '2029-11-30', '2030-01-10', TRUE, FALSE),
('The Bronze Brooch', 'Phasellus suscipit metus at ipsum eleifend, sed ullamcorper nunc luctus. Nulla facilisi. Nam ac odio quis nisi.', 84, FALSE, '2029-12-15', '2023-03-20', TRUE, FALSE),
('The Silver Star', 'Duis feugiat metus id ipsum congue, a luctus dui vestibulum. Aliquam bibendum tincidunt sapien, eget dignissim nisi.', 85, TRUE, '2030-01-20', '2030-03-01', TRUE, FALSE),
('The Iron Idol', 'Curabitur laoreet ligula vitae dolor facilisis, non efficitur sapien sodales. Mauris non justo et mauris lacinia iaculis.', 86, FALSE, '2030-02-10', '2023-03-20', TRUE, FALSE),
('The Platinum Pendant', 'Pellentesque suscipit eros at ligula feugiat varius. Sed id dolor id purus ullamcorper scelerisque.', 87, TRUE, '2030-03-25', '2030-05-05', TRUE, FALSE),
('The Brass Band', 'In id velit a erat accumsan posuere vel eu sem. Integer id libero ac mauris vehicula finibus.', 88, FALSE, '2030-04-10', '2023-03-20', TRUE, FALSE),
('The Copper Crown', 'Nullam hendrerit orci vitae lorem fermentum, id aliquet neque vestibulum. Morbi a erat sed tortor efficitur efficitur.', 89, TRUE, '2030-05-30', '2030-07-10', TRUE, FALSE),
('The Platinum Plaque', 'Vestibulum non neque auctor, interdum risus ac, congue dui. Nulla ac justo nec turpis facilisis fermentum.', 90, FALSE, '2030-06-25', '2023-03-20', TRUE, FALSE),
('The Silver Scroll', 'Phasellus quis turpis non sem maximus tincidunt. Integer rutrum dolor eu lectus consequat aliquam.', 91, TRUE, '2030-07-15', '2030-09-01', TRUE, FALSE),
('The Gold Glove', 'Sed vitae est condimentum, iaculis tortor at, euismod odio. Curabitur nec orci vestibulum, interdum libero ut, aliquet odio.', 92, FALSE, '2030-08-10', '2023-03-20', TRUE, FALSE),
('The Bronze Bow', 'Donec tincidunt quam vel odio tempor, ac vestibulum justo ultricies. Proin id arcu ultrices, viverra eros quis, ultrices est.', 93, TRUE, '2030-09-20', '2030-11-01', TRUE, FALSE),
('The Iron Ingot', 'Vestibulum ut dolor nec enim elementum volutpat. Nullam aliquam quam eget dolor pharetra, nec egestas magna venenatis.', 94, FALSE, '2030-10-05', '2023-03-20', TRUE, FALSE),
('The Bronze Bell', 'Nam sit amet sapien quis est ultricies elementum. Vestibulum ut mi nec nunc facilisis malesuada.', 95, TRUE, '2030-11-30', '2031-01-10', TRUE, FALSE),
('The Iron Helmet', 'Phasellus nec nunc vitae turpis sollicitudin egestas. In rhoncus erat vitae justo faucibus, a dignissim ex rhoncus.', 96, FALSE, '2030-12-15', '2023-03-20', TRUE, FALSE),
('The Copper Cauldron', 'Nullam sagittis libero id diam dictum, ac feugiat lectus gravida. Ut quis quam et enim luctus tempor.', 97, TRUE, '2031-01-20', '2031-03-01', TRUE, FALSE),
('The Brass Bell', 'Sed vestibulum enim vitae tortor mattis fermentum. Nullam efficitur nunc sit amet nunc tincidunt, nec ultrices lacus vehicula.', 98, FALSE, '2031-02-10', '2023-03-20', TRUE, FALSE),
('The Copper Crown', 'Morbi id nulla a est tempus blandit. Ut efficitur dui vitae ante fringilla, auctor feugiat felis aliquam.', 99, TRUE, '2031-03-25', '2031-05-05', TRUE, FALSE),
('The Golden Gauntlet', 'Donec eget enim id sapien ullamcorper fringilla. Cras vitae est eleifend, ultrices risus at, congue libero.', 100, FALSE, '2031-04-10', '2023-03-20', TRUE, FALSE);
