DROP TABLE IF EXISTS story_votes CASCADE;
CREATE TABLE story_votes (
  id SERIAL PRIMARY KEY NOT NULL,
  story_id_id INTEGER REFERENCES stories(id) ON DELETE CASCADE,
  voter_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  vote BOOLEAN DEFAULT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);