DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS stories CASCADE;
CREATE TABLE stories (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_date DATE NOT NULL,
  completed_date DATE NOT NULL,
  public BOOLEAN NOT NULL DEFAULT TRUE,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);

DROP TABLE IF EXISTS contributions CASCADE;
CREATE TABLE contributions (
  id SERIAL PRIMARY KEY NOT NULL,
  story_id INTEGER REFERENCES stories(id) ON DELETE CASCADE,
  story_step SMALLINT NOT NULL,
  content TEXT,
  picked BOOLEAN NOT NULL DEFAULT FALSE,
  contributer_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_date DATE NOT NULL,
  picked_date DATE NOT NULL
);

DROP TABLE IF EXISTS contribution_votes CASCADE;
CREATE TABLE contribution_votes (
  id SERIAL PRIMARY KEY NOT NULL,
  contribution_id INTEGER REFERENCES contributions(id) ON DELETE CASCADE,
  voter_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  vote BOOLEAN DEFAULT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);

DROP TABLE IF EXISTS story_votes CASCADE;
CREATE TABLE story_votes (
  id SERIAL PRIMARY KEY NOT NULL,
  story_id_id INTEGER REFERENCES stories(id) ON DELETE CASCADE,
  voter_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  vote BOOLEAN DEFAULT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);